In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('cars_class.csv')
data

ID  Comp  Circ  D.Circ  Rad.Ra  Pr.Axis.Ra  Max.L.Ra  Scat.Ra  Elong  \
0      1    88    39      70     166          66         7      148     44   
1      2    85    35      64     129          57         6      116     57   
2      3    91    41      84     141          57         9      149     45   
3      4   102    54      98     177          56        10      219     31   
4      5    87    39      74     152          58         6      151     44   
..   ...   ...   ...     ...     ...         ...       ...      ...    ...   
714  715   111    58     105     183          51         6      265     26   
715  716    93    43      76     149          57         7      149     44   
716  717    90    42      63     144          59         7      131     50   
717  718   101    56     101     231          72        10      217     31   
718  719    99    38      74     184          66         6      164     39   

     Pr.Axis.Rect  Max.L.Rect  Sc.Var.Maxis  Sc.Var.maxis  Ra.Gyr  Skew.Maxis  \
0              19         134           167           332     143          69   
1              17         125           138           200     123          65   
2              19         143           170           330     158          72   
3              25         171           219           706     223          72   
4              19         136           174           337     140          70   
..            ...         ...           ...           ...     ...         ...   
714            29         174           285          1018     255          85   
715            19         143           172           335     176          69   
716            18         142           154           259     162          65   
717            24         171           232           698     216          72   
718            20         131           193           414     137          71   

     Skew.maxis  Kurt.maxis  Kurt.Maxis  Holl.Ra  Class  
0             5          13         193      201      0  
1             1          23         196      203      3  
2             9          14         189      199      3  
3             5          17         186      196      1  
4             1          33         187      196      2  
..          ...         ...         ...      ...    ...  
714           4           8         181      183      0  
715          14           0         189      194      2  
716          15           3         197      204      3  
717           2           6         187      197      2  
718           2          22         200      202      0  

[719 rows x 20 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 719 entries, 0 to 718
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            719 non-null    int64
 1   Comp          719 non-null    int64
 2   Circ          719 non-null    int64
 3   D.Circ        719 non-null    int64
 4   Rad.Ra        719 non-null    int64
 5   Pr.Axis.Ra    719 non-null    int64
 6   Max.L.Ra      719 non-null    int64
 7   Scat.Ra       719 non-null    int64
 8   Elong         719 non-null    int64
 9   Pr.Axis.Rect  719 non-null    int64
 10  Max.L.Rect    719 non-null    int64
 11  Sc.Var.Maxis  719 non-null    int64
 12  Sc.Var.maxis  719 non-null    int64
 13  Ra.Gyr        719 non-null    int64
 14  Skew.Maxis    719 non-null    int64
 15  Skew.maxis    719 non-null    int64
 16  Kurt.maxis    719 non-null    int64
 17  Kurt.Maxis    719 non-null    int64
 18  Holl.Ra       719 non-null    int64
 19  Class         719 non-null   

In [ ]:
data.describe()

ID        Comp        Circ      D.Circ      Rad.Ra  Pr.Axis.Ra  \
count  719.000000  719.000000  719.000000  719.000000  719.000000  719.000000   
mean   360.000000   93.435327   44.851182   81.723227  168.579972   61.847010   
std    207.701709    8.111406    6.150286   15.528208   33.809172    8.259136   
min      1.000000   73.000000   33.000000   40.000000  105.000000   47.000000   
25%    180.500000   87.000000   40.000000   70.000000  141.000000   57.000000   
50%    360.000000   93.000000   44.000000   79.000000  166.000000   61.000000   
75%    539.500000   99.000000   49.000000   96.000000  194.500000   65.000000   
max    719.000000  119.000000   59.000000  110.000000  333.000000  138.000000   

         Max.L.Ra     Scat.Ra       Elong  Pr.Axis.Rect  Max.L.Rect  \
count  719.000000  719.000000  719.000000    719.000000  719.000000   
mean     8.625869  168.137691   41.075104     20.531293  148.030598   
std      4.916908   32.937591    7.764459      2.560969   14.560092   
min      2.000000  112.000000   26.000000     17.000000  118.000000   
25%      6.000000  146.000000   33.000000     19.000000  137.000000   
50%      8.000000  157.000000   43.000000     20.000000  146.000000   
75%     10.000000  197.500000   46.000000     23.000000  159.000000   
max     55.000000  265.000000   61.000000     29.000000  188.000000   

       Sc.Var.Maxis  Sc.Var.maxis      Ra.Gyr  Skew.Maxis  Skew.maxis  \
count    719.000000    719.000000  719.000000  719.000000  719.000000   
mean     188.168289    436.215577  174.726008   72.682893    6.343533   
std       31.235395    174.964977   32.149568    7.542055    4.856169   
min      130.000000    184.000000  109.000000   59.000000    0.000000   
25%      167.000000    317.000000  149.000000   68.000000    2.000000   
50%      178.000000    362.000000  174.000000   72.000000    6.000000   
75%      216.000000    584.500000  198.000000   76.000000    9.000000   
max      320.000000   1018.000000  262.000000  135.000000   22.000000   

       Kurt.maxis  Kurt.Maxis     Holl.Ra       Class  
count  719.000000  719.000000  719.000000  719.000000  
mean    12.394993  188.798331  195.407510    1.470097  
std      8.742511    6.048522    7.235166    1.126477  
min      0.000000  176.000000  181.000000    0.000000  
25%      5.500000  184.000000  190.000000    0.000000  
50%     11.000000  188.000000  196.000000    1.000000  
75%     18.000000  193.000000  201.000000    2.000000  
max     41.000000  204.000000  211.000000    3.000000

In [ ]:
x = data.drop(['ID','Class'],axis=1)
y = data['Class']

In [ ]:
x.shape, y.shape

((719, 18), (719,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#Scaling the training data using standard scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)

In [ ]:
#Scaling test data using standard scaler
x_test = sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

LR=LogisticRegression()
KNN=KNeighborsClassifier()
svc=SVC()
DTC=DecisionTreeClassifier()
ABC=AdaBoostClassifier()
GBC=GradientBoostingClassifier()
RFC=RandomForestClassifier()

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix


In [ ]:
#makind an evaluation function
def evaluate_preds(y_true,y_preds):
    accuracy = accuracy_score(y_test,y_preds)

    f1_weighted = f1_score(y_test,y_preds,average='weighted')
    f1_macro = f1_score(y_test,y_preds,average='macro')
    f1_micro = f1_score(y_test,y_preds,average='micro')
    confusion_matrix_result = confusion_matrix(y_true,y_preds)
    metric_dict = {'accuracy':round(accuracy,2),

                   'f1_weighted':round(f1_weighted,2),
                   'f1_macro':round(f1_macro,2),
                   'f1_micro':round(f1_micro,2),
                   'confusion_matrix':confusion_matrix_result}
    print(f'Acc: {accuracy*100:.2f}%')

    print(f'F1_weighted: {f1_weighted:.2f}')
    print(f'F1_macro: {f1_macro:.2f}')
    print(f'F1_micro: {f1_micro:.2f}')
    print(f'Confusion Matrix: \n {confusion_matrix_result}')

    return metric_dict

In [ ]:
np.random.seed(42)
#fitting the model
LR.fit(x_train,y_train)
#making predictions
y_preds = LR.predict(x_test)
#Evaluating on the test set
evaluate_preds(y_test,y_preds);


Acc: 77.78%
F1_weighted: 0.77
F1_macro: 0.78
F1_micro: 0.78
Confusion Matrix: 
 [[34  0  0  1]
 [ 1 19 19  1]
 [ 1  8 24  1]
 [ 0  0  0 35]]


In [ ]:
np.random.seed(42)
#fitting the model
KNN.fit(x_train,y_train)
#making predictions
y_preds = KNN.predict(x_test)
#Evaluating on the test set
evaluate_preds(y_test,y_preds);

Acc: 74.31%
F1_weighted: 0.73
F1_macro: 0.74
F1_micro: 0.74
Confusion Matrix: 
 [[34  0  0  1]
 [ 3 17 18  2]
 [ 2  6 25  1]
 [ 1  0  3 31]]


In [ ]:
np.random.seed(42)
#fitting the model
svc.fit(x_train,y_train)
#making predictions
y_preds = svc.predict(x_test)
#Evaluating on the test set
evaluate_preds(y_test,y_preds);

Acc: 77.08%
F1_weighted: 0.76
F1_macro: 0.77
F1_micro: 0.77
Confusion Matrix: 
 [[34  0  0  1]
 [ 0 19 18  3]
 [ 1  9 23  1]
 [ 0  0  0 35]]


In [ ]:
np.random.seed(42)
#fitting the model
DTC.fit(x_train,y_train)
#making predictions
y_preds = DTC.predict(x_test)
#Evaluating on the test set
evaluate_preds(y_test,y_preds);

Acc: 73.61%
F1_weighted: 0.72
F1_macro: 0.72
F1_micro: 0.74
Confusion Matrix: 
 [[32  0  1  2]
 [ 4 25 10  1]
 [ 4 14 14  2]
 [ 0  0  0 35]]


In [ ]:
np.random.seed(42)
#fitting the model
RFC.fit(x_train,y_train)
#making predictions
y_preds = RFC.predict(x_test)
#Evaluating on the test set
evaluate_preds(y_test,y_preds);

Acc: 72.22%
F1_weighted: 0.71
F1_macro: 0.71
F1_micro: 0.72
Confusion Matrix: 
 [[34  0  0  1]
 [ 1 21 16  2]
 [ 3 15 14  2]
 [ 0  0  0 35]]


In [ ]:
np.random.seed(42)
#fitting the model
GBC.fit(x_train,y_train)
#making predictions
y_preds = GBC.predict(x_test)
#Evaluating on the test set
evaluate_preds(y_test,y_preds);

Acc: 75.69%
F1_weighted: 0.75
F1_macro: 0.75
F1_micro: 0.76
Confusion Matrix: 
 [[34  0  0  1]
 [ 1 22 15  2]
 [ 2 12 18  2]
 [ 0  0  0 35]]


In [ ]:
from inspect import ClassFoundException
from sklearn.model_selection import GridSearchCV
grid = {'penalty': ['l1', 'l2', 'elasticnet', 'none'],
'C': (0.2,0.5,0.7,1),
'solver': ['lbfgs', 'newton-cg', 'liblinear', 'sag', 'saga','newton-cholesky'],
'max_iter': [1000,2000,2500]}

#Instantiate Logistic Regression
#clf = LogisticRegression()

#setting up GridSearchCV
gscv = GridSearchCV(estimator=LR,
                    param_grid=grid,
                    cv=5,
                    verbose=2)

#Fitting the model
gscv.fit(x_train,y_train)



Fitting 5 folds for each of 288 candidates, totalling 1440 fits
[CV] END .....C=0.2, max_iter=1000, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l1, s

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.2, max_iter=1000, penalty=l1, solver=saga; total time=   0.7s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.2, max_iter=1000, penalty=l1, solver=saga; total time=   0.7s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.2, max_iter=1000, penalty=l1, solver=saga; total time=   0.7s
[CV] END C=0.2, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .C=0.2, max_iter=1000, penalty=l2, solver=newton-cg; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.2, max_iter=2000, penalty=l1, solver=saga; total time=   1.4s
[CV] END C=0.2, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.2, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .C=0.2, max_iter=2000, penalty=l2, solver=newton-cg; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.2, max_iter=2500, penalty=l1, solver=saga; total time=   1.0s
[CV] END ......C=0.2, max_iter=2500, penalty=l1, solver=saga; total time=   0.7s
[CV] END ......C=0.2, max_iter=2500, penalty=l1, solver=saga; total time=   0.5s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.2, max_iter=2500, penalty=l1, solver=saga; total time=   0.9s
[CV] END C=0.2, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.2, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.2, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.2, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .C=0.2, max_iter=2500, penalty=l2, solver=newton-cg; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s
[CV] END C=0.5, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.5, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .C=0.5, max_iter=1000, penalty=l2, solver=newton-cg; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=2000, penalty=l1, solver=saga; total time=   0.8s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=2000, penalty=l1, solver=saga; total time=   0.8s
[CV] END ......C=0.5, max_iter=2000, penalty=l1, solver=saga; total time=   0.5s
[CV] END ......C=0.5, max_iter=2000, penalty=l1, solver=saga; total time=   0.7s
[CV] END ......C=0.5, max_iter=2000, penalty=l1, solver=saga; total time=   1.0s
[CV] END C=0.5, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.5, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=2500, penalty=l1, solver=saga; total time=   0.9s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.5, max_iter=2500, penalty=l1, solver=saga; total time=   1.0s
[CV] END ......C=0.5, max_iter=2500, penalty=l1, solver=saga; total time=   0.6s
[CV] END ......C=0.5, max_iter=2500, penalty=l1, solver=saga; total time=   0.5s
[CV] END ......C=0.5, max_iter=2500, penalty=l1, solver=saga; total time=   0.5s
[CV] END C=0.5, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.5, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.5, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.5, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s
[CV] END C=0.7, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.7, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .C=0.7, max_iter=1000, penalty=l2, solver=newton-cg; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=2000, penalty=l1, solver=saga; total time=   0.8s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=2000, penalty=l1, solver=saga; total time=   0.8s
[CV] END ......C=0.7, max_iter=2000, penalty=l1, solver=saga; total time=   0.8s
[CV] END ......C=0.7, max_iter=2000, penalty=l1, solver=saga; total time=   1.0s
[CV] END ......C=0.7, max_iter=2000, penalty=l1, solver=saga; total time=   0.9s
[CV] END C=0.7, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.7, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=2500, penalty=l1, solver=saga; total time=   1.0s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ......C=0.7, max_iter=2500, penalty=l1, solver=saga; total time=   0.9s
[CV] END ......C=0.7, max_iter=2500, penalty=l1, solver=saga; total time=   0.5s
[CV] END ......C=0.7, max_iter=2500, penalty=l1, solver=saga; total time=   0.5s
[CV] END ......C=0.7, max_iter=2500, penalty=l1, solver=saga; total time=   0.5s
[CV] END C=0.7, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=0.7, max_iter=2500, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .....C=0.7, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .....C=0.7, max_iter=2500, penalty=l2, solver=lbfgs; total time=   0.0s
[CV

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ........C=1, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ........C=1, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ........C=1, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ........C=1, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ........C=1, max_iter=1000, penalty=l1, solver=saga; total time=   0.4s
[CV] END C=1, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=1000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .......C=1, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .......C=1, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .......C=1, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .......C=1, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .......C=1, max_iter=1000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END ...C=1, max_iter=1000, penalty=l2, solver=newton-cg; total time=   0.0s
[CV] END ...C

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


[CV] END ........C=1, max_iter=2000, penalty=l1, solver=saga; total time=   1.2s
[CV] END ........C=1, max_iter=2000, penalty=l1, solver=saga; total time=   1.1s
[CV] END ........C=1, max_iter=2000, penalty=l1, solver=saga; total time=   0.9s
[CV] END ........C=1, max_iter=2000, penalty=l1, solver=saga; total time=   0.5s
[CV] END ........C=1, max_iter=2000, penalty=l1, solver=saga; total time=   0.5s
[CV] END C=1, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END C=1, max_iter=2000, penalty=l1, solver=newton-cholesky; total time=   0.0s
[CV] END .......C=1, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .......C=1, max_iter=2000, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END ....

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
960 fits failed out of a total of 1440.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_sol

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': (0.2, 0.5, 0.7, 1),
                         'max_iter': [1000, 2000, 2500],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['lbfgs', 'newton-cg', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             verbose=2)

In [ ]:
gscv.best_params_

{'C': 1, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'lbfgs'}

In [ ]:
gscv.best_estimator_

LogisticRegression(C=1, max_iter=1000)

In [ ]:
gscv.best_score_

np.float64(0.7808695652173914)